<template>
  <div class="title-wrap">
    <h2 class="title">Real-Time Information</h2>
  </div>
  <div class="cnts-common">
    <div class="guide-desc">
      We provide real-time transaction-related information, including execution prices and quote prices, generated by
      KRX's market system to securities companies, information service providers, financial institutions, and other
      market participants.
    </div>
    <div class="title-wrap sub"><h3 class="title">Information Products</h3></div>
    <div class="table">
      <table>
        <caption>
          <strong>Information Products</strong>
        </caption>
        <colgroup>
          <col style="width: 164px" />
          <col />
        </colgroup>
        <thead>
          <tr>
            <th scope="col">Product Name</th>
            <th scope="col">Market Covered</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Securities A</td>
            <td class="left">KOSPI Stock</td>
          </tr>
          <tr>
            <td>Securities B</td>
            <td class="left">KOSDAQ Stock, KONEX Stock</td>
          </tr>
          <tr>
            <td>Securities C</td>
            <td class="left">ETF, ETN, ELW</td>
          </tr>
          <tr>
            <td>Derivatives A</td>
            <td class="left">
              <strong class="txt-md">Stock Index Products : </strong><br />
              KOSPI200 Futures, KOSDAQ150 Futures, KRX300 Futures, Sector Index Futures, Volatility Index Futures,
              Dividend Index Futures, K-New Deal Index Futures, KOSPI200 Options, KOSPI150 Options <br /><br />
              <strong class="txt-md">Equity Products : </strong><br />
              Single Stock Futures, ETF Futures, Single Stock Options <br /><br />
              <strong class="txt-md">Interest Rate Products : </strong><br />
              KTB Futures (3yr/5yr/10yr), Inter-Product Spread <br /><br />
              <strong class="txt-md">Currency Products : </strong><br />
              USD Futures/Options, JPY Futures, EUR Futures, CNY Futures <br /><br />
              <strong class="txt-md">Commodity Products : </strong><br />
              Gold Futures, Lean hog Futures
            </td>
          </tr>
          <tr>
            <td>Derivatives B</td>
            <td class="left">Euro STOXX 50 Index Futures</td>
          </tr>
          <tr>
            <td>Commodities A</td>
            <td class="left">Gold Spot, Emissions</td>
          </tr>
          <tr>
            <td>KRX bonds</td>
            <td class="left">KRX bonds</td>
          </tr>
        </tbody>
      </table>
    </div>
    <ul class="list-info orange">
      <li>
        Please refer to the
        <a href="https://data.koscom.co.kr" class="txt-on" target="_blank">Development Guide (data.koscom.co.kr)</a>
        for details of each Information Product.
      </li>
    </ul>

    <div class="title-wrap sub"><h3 class="title">How to Receive Information</h3></div>
    <div class="title-wrap sub-h4"><h4 class="sub-title">Direct Data Feed</h4></div>
    <div>
      Koscom provides real-time market information stably to securities companies, information service providers,
      financial institutions, and other market participants through a network dedicated to market information.
    </div>
    <div class="title-wrap sub-h5"><h5 class="sub-title">Market information dedicated network STOCK-NET</h5></div>
    <ul class="list dot">
      <li>
        DWDM (800 Gbps) and MSPP (10 GBPS) Dual Backbone provide a direct data feed of market information at high speed.
      </li>
      <li>
        We have our network backup center and provide information without interruption in case of local disasters.
      </li>
      <li>We support checking data reception if necessary through a separate test network.</li>
    </ul>
    <div class="title-wrap sub-h5"><h5 class="sub-title">Internet Network</h5></div>
    <ul class="list dot">
      <li>
        We provide a direct data feed of market information through the public internet network using TCP/IP
        communication.
      </li>
    </ul>
    <div class="title-wrap sub-h4">
      <h4 class="sub-title">Indirect Data Feed through Information Service Providers</h4>
    </div>
    <div>Receive and use real-time market information through an information service provider approved by Koscom.</div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  name: "RealTimeProduct",
  setup() {
    return {};
  },
  data() {
    return {};
  },
  methods: {},
});
</script>
